version: "3"

services:

    backend:
        build: .
        ports:
          - "8000:8000"
        depends_on:
          - database
        volumes:
          - .:/app
        links:
          - "database:postgres"
        environment:
          DB_HOST: database


    database:
        image: postgres:12
        ports:
          - "5432:5432"
        volumes:
          - ./scripts/socketchat.sql:/docker-entrypoint-initdb.d/socketchat.sql
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          